# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

# dependencies via renv: https://rstudio.github.io/renv/articles/ci.html
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

deploy:
  provider: script
  skip_cleanup: true
  script:
  - >
    Rscript
    -e 'account_info <- lapply(paste0("SHINYAPPS_", c("ACCOUNT", "TOKEN", "SECRET")), Sys.getenv)'
    -e 'do.call(rsconnect::setAccountInfo, account_info)'
    -e 'rsconnect::deployApp(appName = "ShinyCICD", appFiles = setdiff(list.files(), "renv"))'
  on:
    branch: master
